# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e8aefe8cbb5a3f15ab6c63cce8acac7f824097a14dcdb815192301b80b4019bf0e7b17bfe2282f4d28504b708c6da33e9dc10841eaeee01f98a0eddf2315da6

test:
  secret_key_base: 4fb40cff4b6013da895bfcce2b9ea25ba2f73c1f78c47d2ddc8e84063c85c74cea782e8b27bca4eee849f6520ff86a0ad306de09182b960b3c86caca784e3503

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
